buildVariable: false
familyName: Noto Sans Caucasian Albanian
googleFonts: true
includeSubsets:
- from: Noto Sans
  name: GF_Latin_Core
recipeProvider: noto
sources:
- NotoSansCaucasianAlbanian.glyphs
